# Generated by Django 5.0.14 on 2025-04-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPoints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpoint',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
