# Generated by Django 5.0.9 on 2025-02-12 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='points.point')),
            ],
        ),
    ]
