# Generated by Django 5.0.12 on 2025-02-27 11:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0003_visitedpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitedpoint',
            name='visit_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
