# Generated by Django 5.0.12 on 2025-04-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0004_alter_visitedpoint_visit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='point_images/'),
        ),
    ]
