# Generated by Django 5.0.12 on 2025-04-01 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0005_point_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='point',
        ),
        migrations.AddField(
            model_name='point',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='points.article'),
        ),
    ]
