# Generated by Django 5.0.14 on 2025-04-25 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0006_remove_article_point_point_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='points.article'),
        ),
        migrations.AlterField(
            model_name='point',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='points.category'),
        ),
    ]
