# Generated by Django 5.0.12 on 2025-02-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_users', models.IntegerField(default=0)),
                ('total_visits', models.IntegerField(default=0)),
                ('visits_per_point', models.JSONField(default=dict)),
                ('top_points', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
